
create table public.finance_entries (
 id bigint generated by default as identity primary key,
 workspace_id uuid not null references public.workspaces(id),
 kind text not null check (kind in ('capital','stock_expense')),
 label text not null check(length(trim(label))>0),
 amount numeric(14,0) not null check(amount>0),
 entry_date date not null default current_date,
 payment_method text not null default 'Cash',
 note text not null default '',
 source_product_id bigint unique,
 seed_key text,
 created_at timestamptz not null default now(),
 unique(workspace_id,seed_key)
);
create index finance_entries_workspace_idx on public.finance_entries(workspace_id);
alter table public.finance_entries enable row level security;
create policy members_read_finance on public.finance_entries for select to authenticated using (
 exists(select 1 from public.members m where m.workspace_id=finance_entries.workspace_id and m.user_id=(select auth.uid()))
);
create policy admins_insert_finance on public.finance_entries for insert to authenticated with check (
 exists(select 1 from public.members m where m.workspace_id=finance_entries.workspace_id and m.user_id=(select auth.uid()) and m.role='admin')
);
create policy admins_update_finance on public.finance_entries for update to authenticated using (
 exists(select 1 from public.members m where m.workspace_id=finance_entries.workspace_id and m.user_id=(select auth.uid()) and m.role='admin')
) with check (
 exists(select 1 from public.members m where m.workspace_id=finance_entries.workspace_id and m.user_id=(select auth.uid()) and m.role='admin')
);
grant select,insert,update on public.finance_entries to authenticated;
grant usage,select on sequence public.finance_entries_id_seq to authenticated;
create function public.finance_summary(p_workspace_id uuid) returns jsonb language sql stable security invoker set search_path='' as $$
 select jsonb_build_object(
 'capital',coalesce((select sum(amount) from public.finance_entries where workspace_id=p_workspace_id and kind='capital'),0),
 'stockSpending',coalesce((select sum(amount) from public.finance_entries where workspace_id=p_workspace_id and kind='stock_expense'),0),
 'received',coalesce((select sum(paid_amount) from public.sales where workspace_id=p_workspace_id),0)
 );
$$;
revoke all on function public.finance_summary(uuid) from public,anon;
grant execute on function public.finance_summary(uuid) to authenticated;
insert into public.finance_entries(workspace_id,kind,label,amount,note,seed_key)
 select w.id,'capital',v.label,30000,'စတင်အရင်း · မှတ်တမ်းတင်သည့်ရက်ကို အသုံးပြုထား',v.seed_key
 from public.workspaces w cross join (values('Han','initial-han'),('Partner','initial-partner')) v(label,seed_key)
 where w.name='Han Digital Sales';
